// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.api';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.api';
import type { ConfirmData, ConfirmErrors, ConfirmResponses, CreateData, CreateErrors, CreateResponses, CurrentData, CurrentErrors, CurrentResponses, CurrentStreakData, CurrentStreakErrors, CurrentStreakResponses, FindActiveData, FindActiveErrors, FindActiveResponses, FindBetweenData, FindBetweenErrors, FindBetweenResponses, MoodTrendData, MoodTrendErrors, MoodTrendResponses, MostMissedHabitsData, MostMissedHabitsErrors, MostMissedHabitsResponses, ReindexData, ReindexErrors, ReindexResponses, ReplayData, ReplayErrors, ReplayResponses, SearchData, SearchErrors, SearchResponses, SetTodayMoodData, SetTodayMoodErrors, SetTodayMoodResponses, SignatureData, SignatureErrors, SignatureResponses, SynchronizeData, SynchronizeErrors, SynchronizeResponses, UpdateTodayHabitData, UpdateTodayHabitErrors, UpdateTodayHabitResponses } from './types.api';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Set today's mood
 *
 * Sets the mood in the authenticated user's entry for today.
 */
export const setTodayMood = <ThrowOnError extends boolean = false>(options: Options<SetTodayMoodData, ThrowOnError>): RequestResult<SetTodayMoodResponses, SetTodayMoodErrors, ThrowOnError> => (options.client ?? client).put<SetTodayMoodResponses, SetTodayMoodErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/entries/today/mood',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Synchronize the current user profile
 *
 * Creates or refreshes the profile for the authenticated Auth0 user. This operation is idempotent.
 */
export const synchronize = <ThrowOnError extends boolean = false>(options?: Options<SynchronizeData, ThrowOnError>): RequestResult<SynchronizeResponses, SynchronizeErrors, ThrowOnError> => (options?.client ?? client).put<SynchronizeResponses, SynchronizeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/profile',
    ...options
});

/**
 * Create an avatar upload signature
 *
 * Creates a signed upload payload for Cloudinary after validating the image content type and size.
 */
export const signature = <ThrowOnError extends boolean = false>(options: Options<SignatureData, ThrowOnError>): RequestResult<SignatureResponses, SignatureErrors, ThrowOnError> => (options.client ?? client).post<SignatureResponses, SignatureErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/me/avatar/upload-signature',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Confirm an uploaded avatar
 *
 * Verifies the uploaded Cloudinary asset and saves it as the current user's avatar.
 */
export const confirm = <ThrowOnError extends boolean = false>(options: Options<ConfirmData, ThrowOnError>): RequestResult<ConfirmResponses, ConfirmErrors, ThrowOnError> => (options.client ?? client).post<ConfirmResponses, ConfirmErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/me/avatar/confirm',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reindex daily entries
 *
 * Rebuilds the daily-entry search index. Requires the X-Maintenance-Key header.
 */
export const reindex = <ThrowOnError extends boolean = false>(options: Options<ReindexData, ThrowOnError>): RequestResult<ReindexResponses, ReindexErrors, ThrowOnError> => (options.client ?? client).post<ReindexResponses, ReindexErrors, ThrowOnError>({
    security: [{ name: 'X-Maintenance-Key', type: 'apiKey' }],
    url: '/internal/cdc/reindex',
    ...options
});

/**
 * Replay a CDC dead letter
 *
 * Replays a failed CDC delivery by ID. Requires the X-Maintenance-Key header.
 */
export const replay = <ThrowOnError extends boolean = false>(options: Options<ReplayData, ThrowOnError>): RequestResult<ReplayResponses, ReplayErrors, ThrowOnError> => (options.client ?? client).post<ReplayResponses, ReplayErrors, ThrowOnError>({
    security: [{ name: 'X-Maintenance-Key', type: 'apiKey' }],
    url: '/internal/cdc/dead-letters/{id}/replay',
    ...options
});

/**
 * List active habits
 *
 * Returns all active habits owned by the authenticated user.
 */
export const findActive = <ThrowOnError extends boolean = false>(options?: Options<FindActiveData, ThrowOnError>): RequestResult<FindActiveResponses, FindActiveErrors, ThrowOnError> => (options?.client ?? client).get<FindActiveResponses, FindActiveErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/habits',
    ...options
});

/**
 * Create a habit
 *
 * Creates a new habit owned by the authenticated user.
 */
export const create = <ThrowOnError extends boolean = false>(options: Options<CreateData, ThrowOnError>): RequestResult<CreateResponses, CreateErrors, ThrowOnError> => (options.client ?? client).post<CreateResponses, CreateErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/habits',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update today's habit log
 *
 * Marks or unmarks a habit in the authenticated user's entry for today.
 */
export const updateTodayHabit = <ThrowOnError extends boolean = false>(options: Options<UpdateTodayHabitData, ThrowOnError>): RequestResult<UpdateTodayHabitResponses, UpdateTodayHabitErrors, ThrowOnError> => (options.client ?? client).patch<UpdateTodayHabitResponses, UpdateTodayHabitErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/entries/today',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get most missed habits
 *
 * Returns the authenticated user's habits ranked by missed completions.
 */
export const mostMissedHabits = <ThrowOnError extends boolean = false>(options?: Options<MostMissedHabitsData, ThrowOnError>): RequestResult<MostMissedHabitsResponses, MostMissedHabitsErrors, ThrowOnError> => (options?.client ?? client).get<MostMissedHabitsResponses, MostMissedHabitsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/stats/most-missed-habits',
    ...options
});

/**
 * Get weekly mood trend
 *
 * Returns the authenticated user's mood trend for the current week. Only `period=week` is currently supported.
 */
export const moodTrend = <ThrowOnError extends boolean = false>(options?: Options<MoodTrendData, ThrowOnError>): RequestResult<MoodTrendResponses, MoodTrendErrors, ThrowOnError> => (options?.client ?? client).get<MoodTrendResponses, MoodTrendErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/stats/mood-trend',
    ...options
});

/**
 * Get the current avatar
 *
 * Returns the authenticated user's current avatar metadata.
 */
export const current = <ThrowOnError extends boolean = false>(options?: Options<CurrentData, ThrowOnError>): RequestResult<CurrentResponses, CurrentErrors, ThrowOnError> => (options?.client ?? client).get<CurrentResponses, CurrentErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/me/avatar',
    ...options
});

/**
 * Get a habit's current streak
 *
 * Calculates the current consecutive-completion streak for one of the authenticated user's habits.
 */
export const currentStreak = <ThrowOnError extends boolean = false>(options: Options<CurrentStreakData, ThrowOnError>): RequestResult<CurrentStreakResponses, CurrentStreakErrors, ThrowOnError> => (options.client ?? client).get<CurrentStreakResponses, CurrentStreakErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/habits/{habitId}/streak',
    ...options
});

/**
 * List entries by date range
 *
 * Returns the authenticated user's daily entries from `from` through `to`, inclusive. Future dates are not allowed.
 */
export const findBetween = <ThrowOnError extends boolean = false>(options: Options<FindBetweenData, ThrowOnError>): RequestResult<FindBetweenResponses, FindBetweenErrors, ThrowOnError> => (options.client ?? client).get<FindBetweenResponses, FindBetweenErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/entries',
    ...options
});

/**
 * Search daily entries
 *
 * Searches the authenticated user's entries by text, optionally limited to an inclusive date range.
 */
export const search = <ThrowOnError extends boolean = false>(options: Options<SearchData, ThrowOnError>): RequestResult<SearchResponses, SearchErrors, ThrowOnError> => (options.client ?? client).get<SearchResponses, SearchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/entries/search',
    ...options
});
