// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type SetMoodRequest = {
    /**
     * Mood score, from 1 (lowest) to 5 (highest)
     */
    score?: number;
    /**
     * Optional labels describing the mood
     */
    tags?: Array<string>;
    /**
     * Optional note for the day
     */
    note?: string;
};

export type ApiError = {
    status?: number;
    code?: string;
    message?: string;
    path?: string;
    errors?: Array<FieldErrorResponse>;
};

export type ApiResponseDailyEntry = {
    success?: boolean;
    data?: DailyEntry;
    error?: ApiError;
    timestamp?: string;
};

export type DailyEntry = {
    id?: string;
    userId?: string;
    date?: string;
    mood?: Mood;
    habits?: Array<HabitLog>;
    createdAt?: string;
    updatedAt?: string;
};

export type FieldErrorResponse = {
    field?: string;
    message?: string;
};

export type HabitLog = {
    habitId?: string;
    done?: boolean;
    note?: string;
};

export type Mood = {
    score?: number;
    tags?: Array<string>;
    note?: string;
};

export type ApiResponseProfileResponse = {
    success?: boolean;
    data?: ProfileResponse;
    error?: ApiError;
    timestamp?: string;
};

export type ProfileResponse = {
    userId?: string;
    email?: string;
    createdAt?: string;
    updatedAt?: string;
};

export type UploadRequest = {
    contentType: 'image/jpeg' | 'image/png' | 'image/webp';
    /**
     * File size in bytes; maximum 5 MiB (5242880 bytes).
     */
    sizeBytes?: number;
};

export type ApiResponseUploadSignature = {
    success?: boolean;
    data?: UploadSignature;
    error?: ApiError;
    timestamp?: string;
};

export type UploadSignature = {
    cloudName?: string;
    apiKey?: string;
    uploadPreset?: string;
    publicId?: string;
    timestamp?: number;
    expiresAt?: string;
    signature?: string;
    uploadUrl?: string;
};

export type ConfirmRequest = {
    publicId: string;
    version?: number;
};

export type ApiResponseAvatar = {
    success?: boolean;
    data?: Avatar;
    error?: ApiError;
    timestamp?: string;
};

export type Avatar = {
    publicId?: string;
    contentType?: string;
    sizeBytes?: number;
    deliveryUrl?: string;
};

export type ApiResponseReindexResult = {
    success?: boolean;
    data?: ReindexResult;
    error?: ApiError;
    timestamp?: string;
};

export type ReindexResult = {
    indexedEntries?: number;
};

export type CreateHabitRequest = {
    /**
     * Habit name
     */
    name: string;
    /**
     * Optional icon or emoji
     */
    icon?: string;
    /**
     * Target completion frequency. Moodly currently supports daily habits only.
     */
    targetFrequency: 'DAILY';
};

export type ApiResponseHabit = {
    success?: boolean;
    data?: Habit;
    error?: ApiError;
    timestamp?: string;
};

export type Habit = {
    id?: string;
    userId?: string;
    name?: string;
    icon?: string;
    targetFrequency?: 'DAILY';
    active?: boolean;
    version?: number;
};

export type HabitVersionRequest = {
    /**
     * Version returned by the latest read
     */
    version: number;
};

export type UpdateHabitRequest = {
    /**
     * Habit name
     */
    name: string;
    /**
     * Optional icon or emoji
     */
    icon?: string;
    /**
     * Version returned by the latest read
     */
    version: number;
};

export type UpdateHabitLogRequest = {
    /**
     * ID of the habit to update
     */
    habitId: string;
    /**
     * Whether the habit was completed today
     */
    done?: boolean;
    /**
     * Optional completion note
     */
    note?: string;
};

export type ApiResponseListMostMissedHabitResponse = {
    success?: boolean;
    data?: Array<MostMissedHabitResponse>;
    error?: ApiError;
    timestamp?: string;
};

export type MostMissedHabitResponse = {
    habitId?: string;
    missedCount?: number;
};

export type ApiResponseListMoodTrendResponse = {
    success?: boolean;
    data?: Array<MoodTrendResponse>;
    error?: ApiError;
    timestamp?: string;
};

export type MoodTrendResponse = {
    date?: string;
    averageScore?: number;
    entryCount?: number;
};

export type ApiResponseListHabit = {
    success?: boolean;
    data?: Array<Habit>;
    error?: ApiError;
    timestamp?: string;
};

export type ApiResponseHabitStreakResponse = {
    success?: boolean;
    data?: HabitStreakResponse;
    error?: ApiError;
    timestamp?: string;
};

export type HabitStreakResponse = {
    habitId?: string;
    currentStreak?: number;
};

export type ApiResponsePageResponseDailyEntry = {
    success?: boolean;
    data?: PageResponseDailyEntry;
    error?: ApiError;
    timestamp?: string;
};

export type PageResponseDailyEntry = {
    items?: Array<DailyEntry>;
    page?: number;
    size?: number;
    totalElements?: number;
    totalPages?: number;
    hasNext?: boolean;
};

export type ApiResponseTodayEntryResponse = {
    success?: boolean;
    data?: TodayEntryResponse;
    error?: ApiError;
    timestamp?: string;
};

export type TodayEntryResponse = {
    date?: string;
    checkedIn?: boolean;
    /**
     * The complete entry, or null when the user has not checked in today.
     */
    entry?: DailyEntry;
};

export type ApiResponsePageResponseEntrySearchResult = {
    success?: boolean;
    data?: PageResponseEntrySearchResult;
    error?: ApiError;
    timestamp?: string;
};

export type EntrySearchResult = {
    entryId?: string;
    date?: string;
    /**
     * Plain-text fragments keyed only by mood.note, habits.note, or mood.tags; ranges use zero-based, end-exclusive offsets.
     */
    highlights?: {
        [key: string]: Array<HighlightFragment>;
    };
};

export type HighlightFragment = {
    text?: string;
    ranges?: Array<HighlightRange>;
};

export type HighlightRange = {
    start?: number;
    end?: number;
};

export type PageResponseEntrySearchResult = {
    items?: Array<EntrySearchResult>;
    page?: number;
    size?: number;
    totalElements?: number;
    totalPages?: number;
    hasNext?: boolean;
};

export type ApiResponseDashboardResponse = {
    success?: boolean;
    data?: DashboardResponse;
    error?: ApiError;
    timestamp?: string;
};

export type DashboardResponse = {
    todayEntry?: DailyEntry;
    activeHabits?: Array<Habit>;
    completedHabitCount?: number;
    totalHabitCount?: number;
    completionRatio?: number;
    weeklyMood?: WeeklyMoodSummary;
    bestCurrentStreak?: number;
};

export type WeeklyMoodSummary = {
    averageScore?: number;
    entryCount?: number;
};

export type ApiResponseApiError = {
    success?: boolean;
    data?: {
        [key: string]: unknown;
    };
    error?: ApiError;
    timestamp?: string;
};

export type SetTodayMoodData = {
    body: SetMoodRequest;
    path?: never;
    query?: never;
    url: '/entries/today/mood';
};

export type SetTodayMoodErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type SetTodayMoodError = SetTodayMoodErrors[keyof SetTodayMoodErrors];

export type SetTodayMoodResponses = {
    /**
     * OK
     */
    200: ApiResponseDailyEntry;
};

export type SetTodayMoodResponse = SetTodayMoodResponses[keyof SetTodayMoodResponses];

export type SynchronizeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/profile';
};

export type SynchronizeErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type SynchronizeError = SynchronizeErrors[keyof SynchronizeErrors];

export type SynchronizeResponses = {
    /**
     * OK
     */
    200: ApiResponseProfileResponse;
};

export type SynchronizeResponse = SynchronizeResponses[keyof SynchronizeResponses];

export type SignatureData = {
    body: UploadRequest;
    path?: never;
    query?: never;
    url: '/me/avatar/upload-signature';
};

export type SignatureErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type SignatureError = SignatureErrors[keyof SignatureErrors];

export type SignatureResponses = {
    /**
     * OK
     */
    200: ApiResponseUploadSignature;
};

export type SignatureResponse = SignatureResponses[keyof SignatureResponses];

export type ConfirmData = {
    body: ConfirmRequest;
    path?: never;
    query?: never;
    url: '/me/avatar/confirm';
};

export type ConfirmErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type ConfirmError = ConfirmErrors[keyof ConfirmErrors];

export type ConfirmResponses = {
    /**
     * OK
     */
    200: ApiResponseAvatar;
};

export type ConfirmResponse = ConfirmResponses[keyof ConfirmResponses];

export type ReindexData = {
    body?: never;
    headers: {
        /**
         * Internal CDC maintenance key.
         */
        'X-Maintenance-Key': string;
    };
    path?: never;
    query?: never;
    url: '/internal/cdc/reindex';
};

export type ReindexErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * A valid X-Maintenance-Key header is required.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type ReindexError = ReindexErrors[keyof ReindexErrors];

export type ReindexResponses = {
    /**
     * OK
     */
    200: ApiResponseReindexResult;
};

export type ReindexResponse = ReindexResponses[keyof ReindexResponses];

export type ReplayData = {
    body?: never;
    headers: {
        /**
         * Internal CDC maintenance key.
         */
        'X-Maintenance-Key': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/internal/cdc/dead-letters/{id}/replay';
};

export type ReplayErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * A valid X-Maintenance-Key header is required.
     */
    403: ApiResponseApiError;
    /**
     * The requested resource was not found.
     */
    404: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type ReplayError = ReplayErrors[keyof ReplayErrors];

export type ReplayResponses = {
    /**
     * CDC dead letter replayed successfully.
     */
    204: void;
};

export type ReplayResponse = ReplayResponses[keyof ReplayResponses];

export type FindByStatusData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Lifecycle filter
         */
        status?: 'active' | 'archived' | 'all';
    };
    url: '/habits';
};

export type FindByStatusErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type FindByStatusError = FindByStatusErrors[keyof FindByStatusErrors];

export type FindByStatusResponses = {
    /**
     * OK
     */
    200: ApiResponseListHabit;
};

export type FindByStatusResponse = FindByStatusResponses[keyof FindByStatusResponses];

export type CreateData = {
    body: CreateHabitRequest;
    path?: never;
    query?: never;
    url: '/habits';
};

export type CreateErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type CreateError = CreateErrors[keyof CreateErrors];

export type CreateResponses = {
    /**
     * Created
     */
    201: ApiResponseHabit;
};

export type CreateResponse = CreateResponses[keyof CreateResponses];

export type RestoreData = {
    body: HabitVersionRequest;
    path: {
        habitId: string;
    };
    query?: never;
    url: '/habits/{habitId}/restore';
};

export type RestoreErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type RestoreError = RestoreErrors[keyof RestoreErrors];

export type RestoreResponses = {
    /**
     * OK
     */
    200: ApiResponseHabit;
};

export type RestoreResponse = RestoreResponses[keyof RestoreResponses];

export type ArchiveData = {
    body: HabitVersionRequest;
    path: {
        habitId: string;
    };
    query?: never;
    url: '/habits/{habitId}/archive';
};

export type ArchiveErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type ArchiveError = ArchiveErrors[keyof ArchiveErrors];

export type ArchiveResponses = {
    /**
     * OK
     */
    200: ApiResponseHabit;
};

export type ArchiveResponse = ArchiveResponses[keyof ArchiveResponses];

export type UpdateData = {
    body: UpdateHabitRequest;
    path: {
        habitId: string;
    };
    query?: never;
    url: '/habits/{habitId}';
};

export type UpdateErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type UpdateError = UpdateErrors[keyof UpdateErrors];

export type UpdateResponses = {
    /**
     * OK
     */
    200: ApiResponseHabit;
};

export type UpdateResponse = UpdateResponses[keyof UpdateResponses];

export type TodayData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/entries/today';
};

export type TodayErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type TodayError = TodayErrors[keyof TodayErrors];

export type TodayResponses = {
    /**
     * OK
     */
    200: ApiResponseTodayEntryResponse;
};

export type TodayResponse = TodayResponses[keyof TodayResponses];

export type UpdateTodayHabitData = {
    body: UpdateHabitLogRequest;
    path?: never;
    query?: never;
    url: '/entries/today';
};

export type UpdateTodayHabitErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type UpdateTodayHabitError = UpdateTodayHabitErrors[keyof UpdateTodayHabitErrors];

export type UpdateTodayHabitResponses = {
    /**
     * OK
     */
    200: ApiResponseDailyEntry;
};

export type UpdateTodayHabitResponse = UpdateTodayHabitResponses[keyof UpdateTodayHabitResponses];

export type MostMissedHabitsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stats/most-missed-habits';
};

export type MostMissedHabitsErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type MostMissedHabitsError = MostMissedHabitsErrors[keyof MostMissedHabitsErrors];

export type MostMissedHabitsResponses = {
    /**
     * OK
     */
    200: ApiResponseListMostMissedHabitResponse;
};

export type MostMissedHabitsResponse = MostMissedHabitsResponses[keyof MostMissedHabitsResponses];

export type MoodTrendData = {
    body?: never;
    path?: never;
    query?: {
        period?: 'week';
    };
    url: '/stats/mood-trend';
};

export type MoodTrendErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type MoodTrendError = MoodTrendErrors[keyof MoodTrendErrors];

export type MoodTrendResponses = {
    /**
     * OK
     */
    200: ApiResponseListMoodTrendResponse;
};

export type MoodTrendResponse2 = MoodTrendResponses[keyof MoodTrendResponses];

export type DeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me/avatar';
};

export type DeleteErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type DeleteError = DeleteErrors[keyof DeleteErrors];

export type DeleteResponses = {
    /**
     * OK
     */
    200: ApiResponseAvatar;
};

export type DeleteResponse = DeleteResponses[keyof DeleteResponses];

export type CurrentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me/avatar';
};

export type CurrentErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type CurrentError = CurrentErrors[keyof CurrentErrors];

export type CurrentResponses = {
    /**
     * OK
     */
    200: ApiResponseAvatar;
};

export type CurrentResponse = CurrentResponses[keyof CurrentResponses];

export type CurrentStreakData = {
    body?: never;
    path: {
        habitId: string;
    };
    query?: never;
    url: '/habits/{habitId}/streak';
};

export type CurrentStreakErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type CurrentStreakError = CurrentStreakErrors[keyof CurrentStreakErrors];

export type CurrentStreakResponses = {
    /**
     * OK
     */
    200: ApiResponseHabitStreakResponse;
};

export type CurrentStreakResponse = CurrentStreakResponses[keyof CurrentStreakResponses];

export type FindBetweenData = {
    body?: never;
    path?: never;
    query: {
        from: string;
        to: string;
        page?: number;
        size?: number;
    };
    url: '/entries';
};

export type FindBetweenErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type FindBetweenError = FindBetweenErrors[keyof FindBetweenErrors];

export type FindBetweenResponses = {
    /**
     * OK
     */
    200: ApiResponsePageResponseDailyEntry;
};

export type FindBetweenResponse = FindBetweenResponses[keyof FindBetweenResponses];

export type SearchData = {
    body?: never;
    path?: never;
    query: {
        q: string;
        from?: string;
        to?: string;
        page?: number;
        size?: number;
    };
    url: '/entries/search';
};

export type SearchErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type SearchError = SearchErrors[keyof SearchErrors];

export type SearchResponses = {
    /**
     * OK
     */
    200: ApiResponsePageResponseEntrySearchResult;
};

export type SearchResponse = SearchResponses[keyof SearchResponses];

export type GetDashboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard';
};

export type GetDashboardErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type GetDashboardError = GetDashboardErrors[keyof GetDashboardErrors];

export type GetDashboardResponses = {
    /**
     * OK
     */
    200: ApiResponseDashboardResponse;
};

export type GetDashboardResponse = GetDashboardResponses[keyof GetDashboardResponses];
