// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type SetMoodRequest = {
    /**
     * Mood score, from 1 (lowest) to 5 (highest)
     */
    score?: number;
    /**
     * Optional labels describing the mood
     */
    tags?: Array<string>;
    /**
     * Optional note for the day
     */
    note?: string;
};

export type ApiError = {
    status?: number;
    code?: string;
    message?: string;
    path?: string;
    errors?: Array<FieldErrorResponse>;
};

export type ApiResponseDailyEntry = {
    success?: boolean;
    data?: DailyEntry;
    error?: ApiError;
    timestamp?: string;
};

export type DailyEntry = {
    id?: string;
    userId?: string;
    date?: string;
    mood?: Mood;
    habits?: Array<HabitLog>;
    createdAt?: string;
    updatedAt?: string;
};

export type FieldErrorResponse = {
    field?: string;
    message?: string;
};

export type HabitLog = {
    habitId?: string;
    done?: boolean;
    note?: string;
};

export type Mood = {
    score?: number;
    tags?: Array<string>;
    note?: string;
};

export type ApiResponseProfileResponse = {
    success?: boolean;
    data?: ProfileResponse;
    error?: ApiError;
    timestamp?: string;
};

export type ProfileResponse = {
    userId?: string;
    email?: string;
    createdAt?: string;
    updatedAt?: string;
};

export type UploadRequest = {
    contentType: string;
    sizeBytes?: number;
};

export type ApiResponseUploadSignature = {
    success?: boolean;
    data?: UploadSignature;
    error?: ApiError;
    timestamp?: string;
};

export type UploadSignature = {
    cloudName?: string;
    apiKey?: string;
    uploadPreset?: string;
    publicId?: string;
    timestamp?: number;
    signature?: string;
    uploadUrl?: string;
};

export type ConfirmRequest = {
    publicId: string;
    version?: number;
};

export type ApiResponseAvatar = {
    success?: boolean;
    data?: Avatar;
    error?: ApiError;
    timestamp?: string;
};

export type Avatar = {
    publicId?: string;
    contentType?: string;
    sizeBytes?: number;
    deliveryUrl?: string;
};

export type ApiResponseReindexResult = {
    success?: boolean;
    data?: ReindexResult;
    error?: ApiError;
    timestamp?: string;
};

export type ReindexResult = {
    indexedEntries?: number;
};

export type CreateHabitRequest = {
    /**
     * Habit name
     */
    name: string;
    /**
     * Optional icon or emoji
     */
    icon?: string;
    /**
     * Target completion frequency
     */
    targetFrequency: string;
};

export type ApiResponseHabit = {
    success?: boolean;
    data?: Habit;
    error?: ApiError;
    timestamp?: string;
};

export type Habit = {
    id?: string;
    userId?: string;
    name?: string;
    icon?: string;
    targetFrequency?: string;
    active?: boolean;
};

export type UpdateHabitLogRequest = {
    /**
     * ID of the habit to update
     */
    habitId: string;
    /**
     * Whether the habit was completed today
     */
    done?: boolean;
    /**
     * Optional completion note
     */
    note?: string;
};

export type ApiResponseListMostMissedHabitResponse = {
    success?: boolean;
    data?: Array<MostMissedHabitResponse>;
    error?: ApiError;
    timestamp?: string;
};

export type MostMissedHabitResponse = {
    habitId?: string;
    missedCount?: number;
};

export type ApiResponseListMoodTrendResponse = {
    success?: boolean;
    data?: Array<MoodTrendResponse>;
    error?: ApiError;
    timestamp?: string;
};

export type MoodTrendResponse = {
    weekStart?: string;
    averageScore?: number;
    entryCount?: number;
};

export type ApiResponseListHabit = {
    success?: boolean;
    data?: Array<Habit>;
    error?: ApiError;
    timestamp?: string;
};

export type ApiResponseHabitStreakResponse = {
    success?: boolean;
    data?: HabitStreakResponse;
    error?: ApiError;
    timestamp?: string;
};

export type HabitStreakResponse = {
    habitId?: string;
    currentStreak?: number;
};

export type ApiResponseListDailyEntry = {
    success?: boolean;
    data?: Array<DailyEntry>;
    error?: ApiError;
    timestamp?: string;
};

export type ApiResponseListEntrySearchResult = {
    success?: boolean;
    data?: Array<EntrySearchResult>;
    error?: ApiError;
    timestamp?: string;
};

export type EntrySearchResult = {
    entryId?: string;
    date?: string;
    highlights?: {
        [key: string]: Array<string>;
    };
};

export type ApiResponseApiError = {
    success?: boolean;
    data?: {
        [key: string]: unknown;
    };
    error?: ApiError;
    timestamp?: string;
};

export type SetTodayMoodData = {
    body: SetMoodRequest;
    path?: never;
    query?: never;
    url: '/entries/today/mood';
};

export type SetTodayMoodErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type SetTodayMoodError = SetTodayMoodErrors[keyof SetTodayMoodErrors];

export type SetTodayMoodResponses = {
    /**
     * OK
     */
    200: ApiResponseDailyEntry;
};

export type SetTodayMoodResponse = SetTodayMoodResponses[keyof SetTodayMoodResponses];

export type SynchronizeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/profile';
};

export type SynchronizeErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type SynchronizeError = SynchronizeErrors[keyof SynchronizeErrors];

export type SynchronizeResponses = {
    /**
     * OK
     */
    200: ApiResponseProfileResponse;
};

export type SynchronizeResponse = SynchronizeResponses[keyof SynchronizeResponses];

export type SignatureData = {
    body: UploadRequest;
    path?: never;
    query?: never;
    url: '/me/avatar/upload-signature';
};

export type SignatureErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type SignatureError = SignatureErrors[keyof SignatureErrors];

export type SignatureResponses = {
    /**
     * OK
     */
    200: ApiResponseUploadSignature;
};

export type SignatureResponse = SignatureResponses[keyof SignatureResponses];

export type ConfirmData = {
    body: ConfirmRequest;
    path?: never;
    query?: never;
    url: '/me/avatar/confirm';
};

export type ConfirmErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type ConfirmError = ConfirmErrors[keyof ConfirmErrors];

export type ConfirmResponses = {
    /**
     * OK
     */
    200: ApiResponseAvatar;
};

export type ConfirmResponse = ConfirmResponses[keyof ConfirmResponses];

export type ReindexData = {
    body?: never;
    headers: {
        /**
         * Internal CDC maintenance key.
         */
        'X-Maintenance-Key': string;
    };
    path?: never;
    query?: never;
    url: '/internal/cdc/reindex';
};

export type ReindexErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * A valid X-Maintenance-Key header is required.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type ReindexError = ReindexErrors[keyof ReindexErrors];

export type ReindexResponses = {
    /**
     * OK
     */
    200: ApiResponseReindexResult;
};

export type ReindexResponse = ReindexResponses[keyof ReindexResponses];

export type ReplayData = {
    body?: never;
    headers: {
        /**
         * Internal CDC maintenance key.
         */
        'X-Maintenance-Key': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/internal/cdc/dead-letters/{id}/replay';
};

export type ReplayErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * A valid X-Maintenance-Key header is required.
     */
    403: ApiResponseApiError;
    /**
     * The requested resource was not found.
     */
    404: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type ReplayError = ReplayErrors[keyof ReplayErrors];

export type ReplayResponses = {
    /**
     * CDC dead letter replayed successfully.
     */
    204: void;
};

export type ReplayResponse = ReplayResponses[keyof ReplayResponses];

export type FindActiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/habits';
};

export type FindActiveErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type FindActiveError = FindActiveErrors[keyof FindActiveErrors];

export type FindActiveResponses = {
    /**
     * OK
     */
    200: ApiResponseListHabit;
};

export type FindActiveResponse = FindActiveResponses[keyof FindActiveResponses];

export type CreateData = {
    body: CreateHabitRequest;
    path?: never;
    query?: never;
    url: '/habits';
};

export type CreateErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type CreateError = CreateErrors[keyof CreateErrors];

export type CreateResponses = {
    /**
     * Created
     */
    201: ApiResponseHabit;
};

export type CreateResponse = CreateResponses[keyof CreateResponses];

export type UpdateTodayHabitData = {
    body: UpdateHabitLogRequest;
    path?: never;
    query?: never;
    url: '/entries/today';
};

export type UpdateTodayHabitErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type UpdateTodayHabitError = UpdateTodayHabitErrors[keyof UpdateTodayHabitErrors];

export type UpdateTodayHabitResponses = {
    /**
     * OK
     */
    200: ApiResponseDailyEntry;
};

export type UpdateTodayHabitResponse = UpdateTodayHabitResponses[keyof UpdateTodayHabitResponses];

export type MostMissedHabitsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stats/most-missed-habits';
};

export type MostMissedHabitsErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type MostMissedHabitsError = MostMissedHabitsErrors[keyof MostMissedHabitsErrors];

export type MostMissedHabitsResponses = {
    /**
     * OK
     */
    200: ApiResponseListMostMissedHabitResponse;
};

export type MostMissedHabitsResponse = MostMissedHabitsResponses[keyof MostMissedHabitsResponses];

export type MoodTrendData = {
    body?: never;
    path?: never;
    query?: {
        period?: string;
    };
    url: '/stats/mood-trend';
};

export type MoodTrendErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type MoodTrendError = MoodTrendErrors[keyof MoodTrendErrors];

export type MoodTrendResponses = {
    /**
     * OK
     */
    200: ApiResponseListMoodTrendResponse;
};

export type MoodTrendResponse2 = MoodTrendResponses[keyof MoodTrendResponses];

export type CurrentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me/avatar';
};

export type CurrentErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type CurrentError = CurrentErrors[keyof CurrentErrors];

export type CurrentResponses = {
    /**
     * OK
     */
    200: ApiResponseAvatar;
};

export type CurrentResponse = CurrentResponses[keyof CurrentResponses];

export type CurrentStreakData = {
    body?: never;
    path: {
        habitId: string;
    };
    query?: never;
    url: '/habits/{habitId}/streak';
};

export type CurrentStreakErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type CurrentStreakError = CurrentStreakErrors[keyof CurrentStreakErrors];

export type CurrentStreakResponses = {
    /**
     * OK
     */
    200: ApiResponseHabitStreakResponse;
};

export type CurrentStreakResponse = CurrentStreakResponses[keyof CurrentStreakResponses];

export type FindBetweenData = {
    body?: never;
    path?: never;
    query: {
        from: string;
        to: string;
    };
    url: '/entries';
};

export type FindBetweenErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type FindBetweenError = FindBetweenErrors[keyof FindBetweenErrors];

export type FindBetweenResponses = {
    /**
     * OK
     */
    200: ApiResponseListDailyEntry;
};

export type FindBetweenResponse = FindBetweenResponses[keyof FindBetweenResponses];

export type SearchData = {
    body?: never;
    path?: never;
    query: {
        q: string;
        from?: string;
        to?: string;
    };
    url: '/entries/search';
};

export type SearchErrors = {
    /**
     * The request is invalid.
     */
    400: ApiResponseApiError;
    /**
     * Authentication is required or the access token is invalid.
     */
    401: ApiResponseApiError;
    /**
     * The authenticated user is not allowed to perform this operation.
     */
    403: ApiResponseApiError;
    /**
     * An unexpected server error occurred.
     */
    500: ApiResponseApiError;
};

export type SearchError = SearchErrors[keyof SearchErrors];

export type SearchResponses = {
    /**
     * OK
     */
    200: ApiResponseListEntrySearchResult;
};

export type SearchResponse = SearchResponses[keyof SearchResponses];
