import { useAuth0 } from '@auth0/auth0-react'
import { Link } from 'react-router'
import { Icon } from '../../../components/ui/Icon.tsx'
import { useDashboard } from '../hooks/useDashboard.ts'

const moodMeta: Record<number, { emoji: string; label: string }> = { 1: { emoji: '😞', label: 'A difficult day' }, 2: { emoji: '😕', label: 'Feeling low' }, 3: { emoji: '😌', label: 'Feeling steady' }, 4: { emoji: '🙂', label: 'Feeling good' }, 5: { emoji: '🤩', label: 'Feeling great' } }

export function DashboardPage() {
  const { user } = useAuth0(); const { data, isLoading, error, reload } = useDashboard(); const firstName = user?.given_name ?? user?.name?.split(' ')[0] ?? 'friend'
  const todayKey = new Date().toLocaleDateString('en-CA'); const today = data?.entries.find((entry) => entry.date === todayKey); const completed = today?.habits?.filter((log) => log.done).length ?? 0; const habitCount = data?.habits.length ?? 0; const completion = habitCount ? Math.round((completed / habitCount) * 100) : 0
  const trend = data?.moodTrend[0]; const bestStreak = Math.max(0, ...(data?.streaks.map((item) => item.currentStreak) ?? [])); const mood = today?.mood?.score ? moodMeta[today.mood.score] : null; const hour = new Date().getHours()
  return <main className="page-container pb-24 lg:pb-10">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Your space</p><h1 className="page-title mt-3">Good {hour < 12 ? 'morning' : hour < 18 ? 'afternoon' : 'evening'}, {firstName} <span aria-hidden="true">🌿</span></h1><p className="page-subtitle">A fresh day to take care of yourself.</p></div><Link className="button-primary" to="/today">{today?.mood ? 'Update check-in' : 'Daily check-in'} <Icon name="arrow-right" className="size-4" /></Link></div>
    {isLoading && <section className="mt-8 grid gap-5 xl:grid-cols-[1.4fr_1fr]" aria-label="Loading dashboard"><div className="card h-72 animate-pulse bg-surface-muted" /><div className="card h-72 animate-pulse bg-surface-muted" /></section>}
    {!isLoading && error && <section className="card mt-8 p-8 text-center" role="alert"><span className="text-4xl">🌧️</span><h2 className="mt-4 text-xl font-bold">Your dashboard needs a moment</h2><p className="mt-2 text-sm text-foreground-muted">{error}</p><button className="button-secondary mt-5" type="button" onClick={() => void reload()}>Try again</button></section>}
    {!isLoading && !error && data && <><section className="mt-8 grid gap-5 xl:grid-cols-[1.4fr_1fr]">
      <article className="card overflow-hidden p-6 sm:p-8"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-foreground-muted">Today’s rhythm</p><h2 className="mt-1 text-2xl font-bold">{habitCount ? completion === 100 ? 'You did it—beautifully' : 'Keep the gentle momentum' : 'Start with one small ritual'}</h2></div><span className="grid size-12 place-items-center rounded-2xl bg-warning-soft text-2xl">{completion === 100 ? '✨' : '☀️'}</span></div><div className="mt-8 flex items-end gap-5"><div className="relative grid size-32 shrink-0 place-items-center rounded-full" style={{ background: `conic-gradient(var(--color-primary) 0 ${completion}%, var(--color-surface-muted) ${completion}% 100%)` }}><div className="grid size-24 place-items-center rounded-full bg-surface text-center"><span><strong className="block text-2xl">{completion}%</strong><span className="text-xs text-foreground-muted">complete</span></span></div></div><div><p className="text-sm leading-6 text-foreground-muted">{habitCount ? <>You’ve completed <strong className="text-foreground">{completed} of {habitCount} habits</strong> today.</> : <>Create a habit that feels small enough to begin today.</>}</p><Link to={habitCount ? '/today' : '/habits'} className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-primary">{habitCount ? 'Open today' : 'Create a habit'} <Icon name="arrow-right" className="size-4" /></Link></div></div></article>
      <article className="card p-6 sm:p-8"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-foreground-muted">Current mood</p><h2 className="mt-1 text-2xl font-bold">{mood?.label ?? 'Not checked in yet'}</h2></div><span className="text-5xl">{mood?.emoji ?? '🌤️'}</span></div>{today?.mood?.note ? <div className="mt-8 rounded-2xl bg-primary-soft p-4"><p className="text-sm italic leading-6 text-primary-dark">“{today.mood.note}”</p></div> : <p className="mt-8 rounded-2xl bg-surface-muted p-4 text-sm leading-6 text-foreground-muted">Take a quiet moment to notice how you’re feeling. There’s no wrong answer.</p>}<Link to="/today" className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-primary">{mood ? 'Update mood' : 'Check in now'} <Icon name="arrow-right" className="size-4" /></Link></article>
    </section><section className="mt-5 grid gap-5 md:grid-cols-3">{[[bestStreak ? '🔥' : '🌱', bestStreak ? `${bestStreak} ${bestStreak === 1 ? 'day' : 'days'}` : 'Start today', 'Best current streak', '/habits'], ['🌈', trend?.averageScore ? `${trend.averageScore.toFixed(1)} / 5` : 'No data yet', 'Weekly mood average', '/stats'], ['📝', String(data.entries.filter((entry) => entry.mood).length), 'Check-ins this week', '/entries']].map(([icon,value,label,to]) => <Link key={label} to={to} className="card flex items-center gap-4 p-5 transition hover:-translate-y-0.5 hover:shadow-lg"><span className="grid size-12 place-items-center rounded-2xl bg-surface-muted text-2xl">{icon}</span><span><strong className="block text-xl">{value}</strong><span className="text-sm text-foreground-muted">{label}</span></span></Link>)}</section></>}
  </main>
}
