import { useStats } from '../hooks/useStats.ts'

export function StatsPage() {
  const { trends, missed, habits, isLoading, error } = useStats()
  const totalEntries = trends.reduce((sum, point) => sum + (point.entryCount ?? 0), 0)
  const average = totalEntries
    ? trends.reduce((sum, point) => sum + (point.averageScore ?? 0) * (point.entryCount ?? 0), 0) / totalEntries
    : 0
  const habitName = (id?: string) => habits.find((habit) => habit.id === id)?.name ?? 'Habit'
  const insight = average >= 4 ? 'Your mood has been bright this week.' : average >= 3 ? 'Your week has felt fairly steady.' : average > 0 ? 'This week may need a little extra care.' : 'Check in to begin seeing your pattern.'
  return <main className="page-container pb-24 lg:pb-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Your patterns</p><h1 className="page-title mt-3">Insights, without judgment</h1><p className="page-subtitle">Notice what supports you and where a little care might help.</p></div><span className="rounded-full border border-border bg-surface px-4 py-2 text-xs font-bold text-foreground-muted">This week</span></div>
    {isLoading && <div className="mt-8 grid gap-5 lg:grid-cols-2" aria-label="Loading insights"><div className="card h-80 animate-pulse bg-surface-muted" /><div className="card h-80 animate-pulse bg-surface-muted" /></div>}
    {!isLoading && error && <div className="card mt-8 p-8 text-center" role="alert"><h2 className="text-xl font-bold">Insights are taking a pause</h2><p className="mt-2 text-sm text-foreground-muted">{error}</p></div>}
    {!isLoading && !error && trends.length === 0 && missed.length === 0 && <div className="card mt-8 p-10 text-center"><span className="text-4xl">🌈</span><h2 className="mt-4 text-xl font-bold">Your patterns will bloom here</h2><p className="mt-2 text-sm text-foreground-muted">Keep checking in; a few entries are all it takes to begin.</p></div>}
    {!isLoading && !error && (trends.length > 0 || missed.length > 0) && <><section className="mt-8 grid gap-4 sm:grid-cols-3">{[['🌈', average ? average.toFixed(1) : '—', 'Average mood'], ['📝', String(totalEntries), 'Check-ins'], ['🌱', String(habits.length), 'Active habits']].map(([icon, value, label]) => <article key={label} className="card p-5"><span className="text-2xl">{icon}</span><strong className="mt-3 block text-2xl">{value}</strong><span className="text-sm text-foreground-muted">{label}</span></article>)}</section>
      <section className="mt-5 grid gap-5 xl:grid-cols-[1.5fr_1fr]"><article className="card p-5 sm:p-7"><div><p className="text-sm font-semibold text-foreground-muted">Mood trend</p><h2 className="mt-1 text-xl font-bold">Your emotional rhythm</h2><p className="mt-2 text-sm text-foreground-muted">{insight}</p></div><div className="mt-8 flex h-56 items-end gap-2 border-b border-border px-1" aria-hidden="true">{trends.map((point) => <div key={point.date} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><span className="text-xs font-bold text-primary">{point.averageScore?.toFixed(1)}</span><div className="w-full max-w-16 rounded-t-lg bg-primary/75 transition hover:bg-primary" style={{ height: `${Math.max(8, ((point.averageScore ?? 0) / 5) * 80)}%` }} /><span className="text-[0.65rem] text-foreground-muted">{point.date ? new Date(`${point.date}T12:00:00`).toLocaleDateString('en-US', { weekday: 'short' }) : '—'}</span></div>)}</div><table className="sr-only"><caption>Daily mood trend for this week</caption><thead><tr><th scope="col">Date</th><th scope="col">Average mood</th><th scope="col">Check-ins</th></tr></thead><tbody>{trends.map((point) => <tr key={point.date}><th scope="row">{point.date || 'Unknown date'}</th><td>{point.averageScore?.toFixed(1) ?? 'No score'}</td><td>{point.entryCount ?? 0}</td></tr>)}</tbody></table></article><article className="card p-5 sm:p-7"><p className="text-sm font-semibold text-foreground-muted">Needs a little love</p><h2 className="mt-1 text-xl font-bold">Most missed habits</h2><div className="mt-6 space-y-5">{missed.slice(0, 5).map((item, index) => { const max = Math.max(1, ...missed.map((candidate) => candidate.missedCount ?? 0)); return <div key={item.habitId}><div className="flex justify-between gap-3 text-sm"><span className="font-semibold">{index + 1}. {habitName(item.habitId)}</span><span className="text-foreground-muted">{item.missedCount ?? 0} missed</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-surface-muted"><div className="h-full rounded-full bg-secondary" style={{ width: `${((item.missedCount ?? 0) / max) * 100}%` }} /></div></div> })}{missed.length === 0 && <p className="text-sm text-foreground-muted">Nothing missed—beautiful consistency.</p>}</div></article></section></>}
  </main>
}
