import { useAuth0 } from '@auth0/auth0-react'
import { useRef, useState, type ChangeEvent } from 'react'
import { Icon } from '../../../components/ui/Icon.tsx'
import { useAvatar } from '../hooks/useAvatar.ts'

const maxFileSize = 5 * 1024 * 1024
export function ProfilePage() {
  const { user, logout } = useAuth0(); const { avatar, isLoading, isUploading, error, upload } = useAvatar(); const fileInput = useRef<HTMLInputElement>(null); const [validation, setValidation] = useState<string | null>(null)
  const name = user?.name ?? 'Moodly user'; const initials = name.split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase()
  function selectFile(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type)) { setValidation('Choose a JPG, PNG, or WebP image.'); return } if (file.size > maxFileSize) { setValidation('Your image must be 5 MB or smaller.'); return } setValidation(null); void upload(file); event.target.value = '' }
  return <main className="page-container pb-24 lg:pb-10"><div className="mx-auto max-w-3xl"><p className="eyebrow">Your account</p><h1 className="page-title mt-3">A space that feels yours</h1><p className="page-subtitle">Manage the personal details that appear around Moodly.</p>
    <section className="card mt-8 overflow-hidden"><div className="h-32 bg-gradient-to-r from-primary-soft via-warning-soft to-secondary/25" /><div className="px-5 pb-7 sm:px-8"><div className="-mt-14 flex flex-wrap items-end justify-between gap-4"><div className="relative"><div className="grid size-28 place-items-center overflow-hidden rounded-full border-4 border-surface bg-primary text-3xl font-bold text-white shadow-lg">{isLoading ? <span className="animate-pulse">••</span> : avatar?.deliveryUrl ? <img className="size-full object-cover" src={avatar.deliveryUrl} alt={`${name}'s avatar`} /> : user?.picture ? <img className="size-full object-cover" src={user.picture} alt={`${name}'s avatar`} referrerPolicy="no-referrer" /> : initials}</div></div><div><input ref={fileInput} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={selectFile} /><button className="button-secondary" type="button" disabled={isUploading} onClick={() => fileInput.current?.click()}>{isUploading ? 'Uploading…' : 'Change photo'}</button></div></div><h2 className="mt-5 text-2xl font-bold">{name}</h2><p className="mt-1 text-sm text-foreground-muted">{user?.email}</p>{(validation || error) && <p className="mt-4 rounded-control bg-red-50 p-3 text-sm text-red-700" role="alert">{validation || error}</p>}<p className="mt-4 text-xs text-foreground-muted">JPG, PNG, or WebP · Maximum 5 MB</p></div></section>
    <section className="card mt-5 divide-y divide-border"><div className="p-5 sm:p-7"><h2 className="text-lg font-bold">Account details</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2"><div><dt className="text-xs font-bold uppercase tracking-wider text-foreground-muted">Name</dt><dd className="mt-1 font-semibold">{name}</dd></div><div><dt className="text-xs font-bold uppercase tracking-wider text-foreground-muted">Email</dt><dd className="mt-1 break-all font-semibold">{user?.email ?? 'Not available'}</dd></div></dl></div><div className="flex flex-wrap items-center justify-between gap-4 p-5 sm:p-7"><div><h2 className="font-bold">Sign out of Moodly</h2><p className="mt-1 text-sm text-foreground-muted">You can always come back whenever you need.</p></div><button type="button" className="button-secondary" onClick={() => logout({ logoutParams: { returnTo: window.location.origin } })}>Log out <Icon name="arrow-right" className="size-4" /></button></div></section>
  </div></main>
}
