import { useSearchParams } from 'react-router'
import { toLocalDateKey } from '../../../utils/date.ts'
import { useEntries } from '../hooks/useEntries.ts'

const moodEmoji: Record<number, string> = { 1: '😞', 2: '😕', 3: '😌', 4: '🙂', 5: '🤩' }
export function EntriesPage() {
  const [params, setParams] = useSearchParams(); const today = new Date(); const monthAgo = new Date(); monthAgo.setDate(monthAgo.getDate() - 30); const defaultTo = toLocalDateKey(today); const defaultFrom = toLocalDateKey(monthAgo); const from = params.get('from') ?? defaultFrom; const to = params.get('to') ?? defaultTo; const { entries, isLoading, error } = useEntries(from, to)
  function changeDate(name: 'from' | 'to', value: string) { const next = new URLSearchParams(params); if (value) next.set(name, value); else next.delete(name); setParams(next) }
  return <main className="page-container pb-24 lg:pb-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Your journal</p><h1 className="page-title mt-3">Moments worth remembering</h1><p className="page-subtitle">A gentle record of how your days have felt.</p></div><div className="card flex flex-wrap gap-3 p-3"><label className="text-xs font-bold text-foreground-muted">From <input type="date" max={to < defaultTo ? to : defaultTo} className="ml-2 rounded-control border border-border px-2 py-1.5 text-foreground" value={from} onChange={(event) => changeDate('from', event.target.value)} /></label><label className="text-xs font-bold text-foreground-muted">To <input type="date" min={from} max={defaultTo} className="ml-2 rounded-control border border-border px-2 py-1.5 text-foreground" value={to} onChange={(event) => changeDate('to', event.target.value)} /></label></div></div><section className="mt-8" aria-live="polite">
    {isLoading && <div className="space-y-4">{[1,2,3].map((item) => <div key={item} className="card h-36 animate-pulse bg-surface-muted" />)}</div>}
    {!isLoading && error && <div className="card p-8 text-center" role="alert"><h2 className="text-lg font-bold">Your entries couldn’t be loaded</h2><p className="mt-2 text-sm text-foreground-muted">{error}</p></div>}
    {!isLoading && !error && entries.length === 0 && <div className="card p-10 text-center"><span className="text-4xl">📝</span><h2 className="mt-4 text-xl font-bold">Your story starts today</h2><p className="mt-2 text-sm text-foreground-muted">Complete a daily check-in and it will appear here.</p></div>}
    {!isLoading && !error && entries.length > 0 && <><p className="mb-4 text-sm font-semibold text-foreground-muted">{entries.length} {entries.length === 1 ? 'entry' : 'entries'} from {new Date(`${from}T12:00:00`).toLocaleDateString()} to {new Date(`${to}T12:00:00`).toLocaleDateString()}</p><div className="space-y-4">{entries.map((entry) => { const date = entry.date ? new Date(`${entry.date}T12:00:00`) : null; const done = entry.habits?.filter((habit) => habit.done).length ?? 0; return <article className="card p-5 sm:p-6" key={entry.id ?? entry.date}><div className="flex gap-4"><span className="text-4xl">{entry.mood?.score ? moodEmoji[entry.mood.score] : '📝'}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-xs font-bold uppercase tracking-wider text-foreground-muted">{date?.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}</p><h2 className="mt-1 font-bold">{entry.mood?.score ? `Mood ${entry.mood.score} of 5` : 'Habit check-in'}</h2></div><span className="rounded-full bg-success/10 px-3 py-1 text-xs font-bold text-success">{done} habits complete</span></div>{entry.mood?.note && <p className="mt-4 text-sm leading-6 text-foreground-muted">{entry.mood.note}</p>}{entry.mood?.tags && entry.mood.tags.length > 0 && <div className="mt-4 flex flex-wrap gap-2">{entry.mood.tags.map((tag) => <span key={tag} className="rounded-full bg-surface-muted px-2.5 py-1 text-xs font-semibold">{tag}</span>)}</div>}</div></div></article> })}</div></>}
  </section></main>
}
