import { useEffect, useState } from 'react'
import { getUserFacingError } from '../../../api/errorMessages.ts'
import { Icon } from '../../../components/ui/Icon.tsx'
import { useTodayEntry } from '../hooks/useTodayEntry.ts'

const moods = [{ score: 1, emoji: '😞', label: 'Rough' }, { score: 2, emoji: '😕', label: 'Low' }, { score: 3, emoji: '😌', label: 'Okay' }, { score: 4, emoji: '🙂', label: 'Good' }, { score: 5, emoji: '🤩', label: 'Great' }]
const tags = ['Calm', 'Energized', 'Grateful', 'Tired', 'Anxious', 'Focused']
type MutationMessage = { text: string; kind: 'success' | 'error' }

function MutationLiveRegion({ message, label }: { message: MutationMessage | null; label: string }) {
  return <div aria-label={label} aria-live={message?.kind === 'error' ? 'assertive' : 'polite'} aria-atomic="true">{message && <p className={`text-sm ${message.kind === 'error' ? 'text-red-700' : 'text-foreground-muted'}`}>{message.text}</p>}</div>
}

export function TodayPage() {
  const { entry, habits, isLoading, error, updateMood, toggleHabit } = useTodayEntry()
  const [score, setScore] = useState<number | null>(null); const [note, setNote] = useState(''); const [selectedTags, setSelectedTags] = useState<string[]>([]); const [isSaving, setIsSaving] = useState(false); const [savingHabitId, setSavingHabitId] = useState<string | null>(null); const [moodMessage, setMoodMessage] = useState<MutationMessage | null>(null); const [habitMessage, setHabitMessage] = useState<MutationMessage | null>(null)
  useEffect(() => {
    if (!entry?.mood) return
    const mood = entry.mood
    queueMicrotask(() => { setScore(mood.score ?? null); setNote(mood.note ?? ''); setSelectedTags(mood.tags ?? []) })
  }, [entry])
  const completed = new Set(entry?.habits?.filter((log) => log.done).map((log) => log.habitId))
  async function save() { if (!score) { setMoodMessage({ text: 'Choose how you feel first.', kind: 'error' }); return } setIsSaving(true); setMoodMessage(null); try { await updateMood({ score, note: note.trim() || undefined, tags: selectedTags }); setMoodMessage({ text: 'Your check-in is saved. Be proud of showing up.', kind: 'success' }) } catch (reason) { setMoodMessage({ text: getUserFacingError(reason, 'Unable to save your check-in.'), kind: 'error' }) } finally { setIsSaving(false) } }
  async function changeHabit(habitId: string, done: boolean) { setSavingHabitId(habitId); setHabitMessage(null); try { await toggleHabit(habitId, done); setHabitMessage({ text: done ? 'Habit completed—nice work.' : 'Habit marked as not complete.', kind: 'success' }) } catch (reason) { setHabitMessage({ text: getUserFacingError(reason, 'Unable to update this habit.'), kind: 'error' }) } finally { setSavingHabitId(null) } }
  if (isLoading) return <main className="page-container"><div className="card h-96 animate-pulse bg-surface-muted" aria-label="Loading today’s check-in" /></main>
  if (error) return <main className="page-container"><div className="card p-8 text-center" role="alert"><h1 className="text-xl font-bold">Today isn’t available yet</h1><p className="mt-2 text-sm text-foreground-muted">{error}</p></div></main>
  return <main className="page-container pb-24 lg:pb-10"><div className="mx-auto max-w-3xl"><p className="eyebrow">Daily check-in</p><h1 className="page-title mt-3">How’s your inner weather?</h1><p className="page-subtitle">No right answer—just a small moment of honesty.</p>
    <section className="card mt-8 p-5 sm:p-8"><h2 className="text-lg font-bold">Right now, I feel…</h2><div className="mt-5 grid grid-cols-5 gap-2 sm:gap-3">{moods.map((mood) => <button key={mood.score} type="button" onClick={() => setScore(mood.score)} aria-pressed={score === mood.score} className={`flex min-h-24 flex-col items-center justify-center rounded-2xl border text-3xl transition ${score === mood.score ? 'border-primary bg-primary-soft ring-3 ring-primary/10' : 'border-border bg-background hover:border-primary/50'}`}><span>{mood.emoji}</span><span className="mt-2 text-[0.65rem] font-bold sm:text-xs">{mood.label}</span></button>)}</div><h2 className="mt-8 text-sm font-bold">What’s shaping this feeling?</h2><div className="mt-3 flex flex-wrap gap-2">{tags.map((tag) => <button type="button" key={tag} aria-pressed={selectedTags.includes(tag)} onClick={() => setSelectedTags((current) => current.includes(tag) ? current.filter((item) => item !== tag) : [...current, tag])} className={`rounded-full border px-3 py-2 text-xs font-semibold ${selectedTags.includes(tag) ? 'border-primary bg-primary-soft text-primary-dark' : 'border-border'}`}>{tag}</button>)}</div><label className="field-label mt-8" htmlFor="reflection">A note to yourself <span className="font-normal text-foreground-muted">(optional)</span></label><textarea id="reflection" className="field-input min-h-28 resize-y" value={note} maxLength={500} placeholder="What would you like to remember about today?" onChange={(event) => setNote(event.target.value)} /><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><MutationLiveRegion message={moodMessage} label="Check-in update" /><button type="button" className="button-primary" disabled={isSaving} onClick={() => void save()}>{isSaving ? 'Saving…' : 'Save check-in'} <Icon name="check" className="size-4" /></button></div></section>
    <section className="mt-8"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Today’s habits</h2><span className="text-sm font-bold text-primary">{completed.size} of {habits.length}</span></div><div className="mt-3"><MutationLiveRegion message={habitMessage} label="Habit update" /></div><div className="mt-4 space-y-3">{habits.length === 0 ? <div className="card p-6 text-center text-sm text-foreground-muted">No active habits yet. Add one from the Habits page.</div> : habits.map((habit) => { const done = completed.has(habit.id); const saving = savingHabitId === habit.id; return <button type="button" key={habit.id} aria-pressed={done} disabled={savingHabitId !== null} className="card flex w-full items-center gap-4 p-4 text-left transition hover:border-primary/40 disabled:cursor-wait disabled:opacity-70" onClick={() => habit.id && void changeHabit(habit.id, !done)}><span className="grid size-11 place-items-center rounded-xl bg-surface-muted text-xl">{habit.icon || '🌿'}</span><span className={`flex-1 font-semibold ${done ? 'text-foreground-muted line-through' : ''}`}>{habit.name}</span><span className={`grid size-7 place-items-center rounded-full ${done ? 'bg-success text-white' : 'border-2 border-border'}`} aria-hidden="true">{saving ? <span className="size-3 animate-spin rounded-full border-2 border-current border-t-transparent" /> : done && <Icon name="check" className="size-4" />}</span></button> })}</div></section>
  </div></main>
}
