import { useState, type FormEvent } from 'react'
import { Link, useSearchParams } from 'react-router'
import { Icon } from '../../../components/ui/Icon.tsx'
import { useEntrySearch } from '../hooks/useEntrySearch.ts'

export function SearchPage() {
  const [params, setParams] = useSearchParams(); const query = params.get('q') ?? ''; const from = params.get('from') ?? ''; const to = params.get('to') ?? ''; const [draft, setDraft] = useState(query); const { results, isLoading, error } = useEntrySearch(query, from, to)
  const invalidRange = Boolean(from && to && from > to)
  function submit(event: FormEvent) { event.preventDefault(); const next = new URLSearchParams(params); if (draft.trim()) next.set('q', draft.trim()); else next.delete('q'); setParams(next) }
  function setDate(name: 'from' | 'to', value: string) { const next = new URLSearchParams(params); if (value) next.set(name, value); else next.delete(name); setParams(next) }
  return <main className="page-container pb-24 lg:pb-10"><div className="mx-auto max-w-4xl"><p className="eyebrow">Look back</p><h1 className="page-title mt-3">Find a moment</h1><p className="page-subtitle">Search the words and feelings you’ve captured along the way.</p>
    <form className="card mt-8 p-3" onSubmit={submit}><div className="flex items-center gap-2"><Icon name="search" className="ml-2 size-5 shrink-0 text-foreground-muted" /><label className="sr-only" htmlFor="search-input">Search entries</label><input id="search-input" className="min-h-12 min-w-0 flex-1 bg-transparent px-2 text-base outline-none" value={draft} placeholder="Try “walk”, “grateful”, or “work”…" onChange={(event) => setDraft(event.target.value)} /><button className="button-primary" type="submit">Search</button></div><div className="mt-2 flex flex-wrap items-center gap-3 border-t border-border px-2 pt-3"><label className="text-xs font-bold text-foreground-muted">From <input type="date" max={to || undefined} className="ml-2 rounded-control border border-border px-2 py-1.5 text-foreground" value={from} onChange={(event) => setDate('from', event.target.value)} /></label><label className="text-xs font-bold text-foreground-muted">To <input type="date" min={from || undefined} className="ml-2 rounded-control border border-border px-2 py-1.5 text-foreground" value={to} onChange={(event) => setDate('to', event.target.value)} /></label>{(from || to) && <button type="button" className="text-xs font-bold text-primary" onClick={() => { const next = new URLSearchParams(params); next.delete('from'); next.delete('to'); setParams(next) }}>Clear dates</button>}</div>{invalidRange && <p className="px-2 pt-3 text-xs font-semibold text-red-700" role="alert">The start date must be before the end date.</p>}</form>
    <section className="mt-8" aria-live="polite">{!query && <div className="py-14 text-center"><span className="mx-auto grid size-16 place-items-center rounded-full bg-primary-soft text-3xl">🔎</span><h2 className="mt-5 text-xl font-bold">What’s on your mind?</h2><p className="mt-2 text-sm text-foreground-muted">Search for a feeling, activity, person, or memory.</p></div>}{query && !invalidRange && isLoading && <div className="space-y-3">{[1,2,3].map((item) => <div key={item} className="card h-28 animate-pulse bg-surface-muted" />)}</div>}{query && !invalidRange && !isLoading && error && <div className="card p-8 text-center" role="alert"><h2 className="text-lg font-bold">Search hit a snag</h2><p className="mt-2 text-sm text-foreground-muted">{error}</p></div>}{query && !invalidRange && !isLoading && !error && results.length === 0 && <div className="card p-10 text-center"><span className="text-4xl">🍃</span><h2 className="mt-4 text-xl font-bold">No moments matched “{query}”</h2><p className="mt-2 text-sm text-foreground-muted">Try a shorter phrase or clear the date filters.</p></div>}{query && !invalidRange && !isLoading && !error && results.length > 0 && <><p className="mb-4 text-sm font-semibold text-foreground-muted">{results.length} {results.length === 1 ? 'moment' : 'moments'} found for “{query}”</p><div className="space-y-3">{results.map((result) => <article key={result.entryId} className="card p-5"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs font-bold uppercase tracking-wider text-primary">{result.date ? new Date(`${result.date}T12:00:00`).toLocaleDateString('en-US', { weekday: 'short', month: 'long', day: 'numeric' }) : 'Journal entry'}</p><Link className="text-xs font-bold text-primary" to={`/entries?from=${result.date ?? ''}&to=${result.date ?? ''}`}>View in journal</Link></div><div className="mt-4 space-y-2">{Object.entries(result.highlights ?? {}).flatMap(([field, values]) => values.map((fragment, index) => <p key={`${field}-${index}`} className="rounded-xl bg-surface-muted p-3 text-sm leading-6"><span className="mr-2 font-bold capitalize text-foreground-muted">{field}:</span>{fragment.text}</p>))}</div></article>)}</div></>}</section>
  </div></main>
}
